# 馬可夫鍊（MM）

### 我們以白球W與黑球B為例子

![title](MM.png)

In [4]:
import numpy as np

In [8]:
# 起始狀態
I = np.matrix([[1, 0]])
# 轉移矩陣
T = np.matrix([[.7, 0.3],
               [.6, 0.4]])
T1 = I * T
# 第一次轉移
print (T1)


[[0.7 0.3]]


In [9]:
T2 = T1 * T
# 第二次轉移
print (T2)

[[0.67 0.33]]


In [10]:

T3 = T2 * T
# 第三次轉移
print (T3)

[[0.667 0.333]]


In [11]:
# 起始狀態2
I = np.matrix([[0.5, 0.5]])
# 轉移矩陣
T = np.matrix([[.7, 0.3],
               [.6, 0.4]])
T1 = I * T
# 第一次轉移
print (T1)

[[0.65 0.35]]


In [12]:

T2 = T1 * T
# 第二次轉移
print (T2)

[[0.665 0.335]]


In [13]:

T3 = T2 * T
# 第三次轉移
print (T3)

[[0.6665 0.3335]]
